### ISSUE TITLE
Not able to run test by ember exam in split mode.

### ISSUE THREAD

**Issue by gaurav0210** [trentmwillis/ember-exam#103]
Hi
I have installed ember exam updated ember-cli-qunit@4 and test_helper.js but I am not able to run tests in split mode using ember exam. It gives so many errors. Please suggest what could be the reason for this.

//test-helper.js
import resolver from './helpers/resolver';
import registerSelectHelper from './helpers/register-select-helper';
registerSelectHelper();
import {
setResolver,
} from 'ember-qunit';
import loadEmberExam from 'ember-exam/test-support/load';
loadEmberExam();
import { start } from 'ember-cli-qunit';
start();
window.cup_ = _;
setResolver(resolver);

//Tried
ember exam -s --split=2 --parallel
ember exam -s --split=2 --parallel --filter='acceptance'

<img width="1193" alt="screen shot 2017-08-18 at 10 23 47 am" src="https://user-images.githubusercontent.com/11131500/29444858-94ea1634-8400-11e7-9eae-8be734d373a8.png">
<img width="723" alt="screen shot 2017-08-18 at 10 25 08 am" src="https://user-images.githubusercontent.com/11131500/29444863-9a61297c-8400-11e7-8e39-a461ce72d739.png">
<img width="542" alt="screen shot 2017-08-18 at 10 25 39 am" src="https://user-images.githubusercontent.com/11131500/29444865-9cf5c706-8400-11e7-968c-3ded7ebc1735.png">

**Comment by gaurav0210** [comment]
Hi @trentmwillis,
Please suggest anything for this, as this is a blocker for me. Thanks

**Comment by trentmwillis** [comment]
All that ember-exam does is split up which test modules are run by your application. If errors result from the split, then that means your tests are not independent of each other and are currently dependent on the order in which they are run.

In the error you have posted above, the issue appears to be that your test is expecting a `/api/profiles` endpoint to be setup, but it is not.

Since this problem appears to be with your application and not this addon, I'll be closing this issue. For further support, you might want to try the [Ember Community Slack](https://ember-community-slackin.herokuapp.com/).
