### ISSUE TITLE
ember exam --split 8 --split-file=1 --server fails to split

### ISSUE THREAD

**Issue by stefanpenner** [trentmwillis/ember-exam#13]
it appears

```sj
ember exam --split 8 --split-file=1 --server
```

Doesn't correctly split, rather the resulting test run, runs all tests.

**Comment by trentmwillis** [comment]
This is due to the fact that the test file processing is done by [patching the Build task](https://github.com/trentmwillis/ember-exam/blob/master/lib/commands/exam.js#L55-L56) and the test server [uses a Builder directly](https://github.com/ember-cli/ember-cli/blob/master/lib/commands/test.js#L140) instead of a Build task, thus the processing never occurs.

I'm thinking we could get around this by tapping into the [`Builder#build`](https://github.com/ember-cli/ember-cli/blob/master/lib/models/builder.js#L154) method and chaining it on there, since `build` is called in both cases. Will try to test that out some time this week.

**Comment by trentmwillis** [comment]
Closed via #20, this is now supported by using the `--use-ast=false` flag. This will eventually become the default after a bit more testing.
