### ISSUE TITLE
Idea: augment test-loader, rather then modifying the build

### ISSUE THREAD

**Issue by stefanpenner** [trentmwillis/ember-exam#15]
What if, instead of dropping modules form the build, instead this library augmented the test-loader to load files corresponding to the current partition.

maybe augmenting -> https://github.com/ember-cli/ember-cli-test-loader/blob/master/addon-test-support/index.js#L33-L40

**Comment by trentmwillis** [comment]
This is a good idea. I had mentioned in #9 that I don't think splitting the tests should be a concern of this addon. But, until we can get support from the actual test framework, moving the splitting into a modification of the `test-loader` would be a good compromise:

> Lastly, test splitting should most likely be a test framework concern as it can re-order and balance tests better (since it understands the test constructs).

Eventually I'd like to see this addon more-or-less be a simple wrapper for passing proper config values.

**Comment by stefanpenner** [comment]
Test framework support sounds great, likely something a-bit more long term.

If I add support to test-loader, what would be best. Should it understand query-params ? Maybe something like `_split=8&_partition=1&weighted=true/false` ?

**Comment by stefanpenner** [comment]
Well, actually I suspect this library may be able to just augment the test-loader (we can make some public API for providing the test-loader a strategy.

**Comment by trentmwillis** [comment]
I think the existing interface should be fine. Since we can [add a custom include/exclude filter](https://github.com/ember-cli/ember-cli-test-loader/blob/master/addon-test-support/index.js#L7-L13) to do the splitting.

We'll need to parse the information from the query params, but we could implement that in this addon unless you see a need to make that a concern of the `TestLoader`.

**Comment by stefanpenner** [comment]
> We'll need to parse the information from the query params, but we could implement that in this addon unless you see a need to make that a concern of the TestLoader.

nope, this is fine here.

Should i explore this tomorrow, or are you interested?

**Comment by trentmwillis** [comment]
Feel free to explore it. Otherwise, I probably can get to it some time later this week.

**Comment by trentmwillis** [comment]
@stefanpenner after thinking about this some more, I think a modification to `TestLoader` might be needed. It would be nice if `TestLoader` identified all the modules it was going to load and then loaded them, rather than loading modules one-by-one as they're identified. So essentially:

```js
TestLoader.prototype.loadModules = function() {
  var modules = this.getTestModules();
  this.requireModules(modules);
};
```

The reason for this is that if we try to split up modules one at a time, we have to first identify if they meet all the other test module matchers and then assign them to a group (essentially recreating the work the TestLoader is doing). Basically, I think we want the logic for identifying a test to be separate from partitioning a test.

In the above, we can hook into `requireModules` or expose another hook for modifying the `modules` array. Does this make sense? If so, I can implement the changes for TestLoader.

**Comment by stefanpenner** [comment]
@trentmwillis sounds good
