### ISSUE TITLE
--split filters out non-test files in tests/

### ISSUE THREAD

**Issue by jamesarosen** [trentmwillis/ember-exam#4]
I have files in tests like `tests/fixtures/blog-posts.js`. When I use `--split=4 --split-file=<1,2,3,4>`, they get filtered out of some runs, causing test failures.

**Comment by trentmwillis** [comment]
[This is the culprit](https://github.com/trentmwillis/ember-exam/blob/master/lib/utils/tests-processor.js#L13-L15). The intent is that test helpers should be included in all bundles so I filter them out, but this means that that anything that is not a test helper gets broken up as if it is a test. Obviously this is incorrect.

We can reverse the logic to assume anything that is not a test should be included in all bundles. A PR would be welcome, otherwise I will try to get to this sometime this week. (Also need to write tests for this at some point.)

**Comment by trentmwillis** [comment]
Released v0.1.1, should be fixed.

**Comment by jamesarosen** [comment]
:tada:
