### ISSUE TITLE
Parallel nested inside of partition?

### ISSUE THREAD

**Issue by bendemboski** [trentmwillis/ember-exam#62]
I have a project that really needs refactoring, but currently has a very large number of tests that take a long time to run. I use CircleCI's parallel containers feature along with some custom code that I wrote that achieves the same effect as your partitioning. I suspect that I'm not maxing out the resources in each container, though, so what I'd love to try is partitioning my tests across containers, and then in each container parallelizing the tests in its partition.

Good idea? Silly idea? I'd probably be willing to take a crack at implementing it in a PR if you tell me if you think it's a good idea and help me figure out the API (CLI) design.

**Comment by trentmwillis** [comment]
This seems like a great idea to maximize and yet another good way to scale when you have a large test suite. That said, I would think about it differently. Rather than thinking in terms of parallelized partitions inside of other partitions, I would think of them as parallelized partitions distributed.

What I mean by this is that we don't want:

```
Partition #1
- Sub-partition #1
- Sub-partition #2
---
Partition #2
- Sub-partition #1
- Sub-partition #2
```

We just want:

```
Partition #1
Partition #2
---
Partition #3
Partition #4
```

Which I think lends itself to an easy/intuitive API. We already have the `--partition` option, so we can just allow that to support taking an array of partitions:

```bash
ember exam --split 4 --partition 1,2 --parallel
```

The exact semantics of the "array" would be determined the whatever Ember-CLI's underlying arg-parsing lib is. Should probably also support calling it `--partitions` (note the `s`).

**Comment by bendemboski** [comment]
Okay, I took a stab at it in #63
