### ISSUE TITLE
Random percentage of tests

### ISSUE THREAD

**Issue by deepan83** [trentmwillis/ember-exam#78]
Is there a way to run a random % of tests through exam? Like for example, randomly selected 25% of the tests.

**Comment by trentmwillis** [comment]
Not currently. What is the use case you're trying to satisfy?

**Comment by deepan83** [comment]
At the moment, we are limited on the number of CI agents for our tests, so we intend to run a 'light' version of our test suite where appropriate

**Comment by trentmwillis** [comment]
I would recommend investing in figuring out why your test suite can't be handled by your CI or simply run all your tests on one machine instead of using multiple CI agents.

Running only random portions of your test suite will allow regressions to slip in undetected and will likely cause more difficultly and frustration in maintaining your code over the long run. Therefore, unless another use case is presented, I don't think this is a feature we'll support "out-of-the-box" with ember-exam.
